sudo: required
language: node_js,csharp
node_js:
  - "stable"
mono: none
dotnet: 2.1.402
cache:
  directories:
    - node_modules
script:
  - cd frontend
  - npm i yarn -g
  - yarn
  - yarn build
  - cd ../backend
  - dotnet restore
  - dotnet build
