sudo: required
dist: trusty
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1
script:
  - cd frontend
  - npm i yarn -g
  - yarn
  - yarn build
  - cd ../backend-datamodel
  - dotnet restore
  - dotnet build
  - cd ../database-filling-tool
  - dotnet restore
  - dotnet build
  - cd ../backend
  - dotnet restore
  - dotnet build
